name: cprogram
channels:
    - conda-forge
dependencies:
    - python=3
    - gcc
    - pip=19.2.1
    - jupyter
    - notebook
    - pip:
        - jupyter-c-kernel==1.2.2
        
    - install_c_kernel --sys-prefix
